Fix incorrect argparse types for --output and --material.
Using `nargs=1` was wrong because that turns the argument into a list type,
so the below `output_name = args.output` would have `output_name` be a list,
not a file path string as intended.

Fixes crash:

      File "objuvpacker.py", line 110, in main
        outname = output_name+"_full.png"
    TypeError: can only concatenate list (not "str") to list